------------- Homework #1 -------------

------------- RIGHT OUTER JOIN -------------
SELECT P.NOME, C.NUMERO 
FROM PESSOA P 
RIGHT OUTER JOIN CONTATO C ON (C.ID_PESSOA = P.ID_PESSOA);

SELECT P.NOME, E.LOGRADOURO
FROM PESSOA P
RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (P.ID_PESSOA = PXPE.ID_PESSOA)
RIGHT OUTER JOIN ENDERECO_PESSOA e ON (E.ID_ENDERECO= PXPE.ID_ENDERECO);

SELECT P.NOME, E.LOGRADOURO, C.NUMERO 
FROM PESSOA P
RIGHT OUTER JOIN CONTATO c  ON (C.ID_PESSOA = P.ID_PESSOA)
RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (P.ID_PESSOA = PXPE.ID_PESSOA)
RIGHT OUTER JOIN ENDERECO_PESSOA e ON (E.ID_ENDERECO = PXPE.ID_ENDERECO);


------------- FULL OUTER JOIN -------------
SELECT P.NOME, C.NUMERO 
FROM PESSOA P 
full OUTER JOIN CONTATO C ON (C.ID_PESSOA = P.ID_PESSOA);

SELECT P.NOME, E.LOGRADOURO
FROM PESSOA P
full OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (P.ID_PESSOA = PXPE.ID_PESSOA)
full OUTER JOIN ENDERECO_PESSOA e ON (E.ID_ENDERECO= PXPE.ID_ENDERECO);

SELECT P.NOME, E.LOGRADOURO, C.NUMERO 
FROM PESSOA P
full OUTER JOIN CONTATO c  ON (C.ID_PESSOA = P.ID_PESSOA)
full OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (P.ID_PESSOA = PXPE.ID_PESSOA)
full OUTER JOIN ENDERECO_PESSOA e ON (E.ID_ENDERECO= PXPE.ID_ENDERECO);

------------- EXISTS -------------
SELECT p.nome 
FROM PESSOA p 
WHERE EXISTS ( SELECT PXPE.id_pessoa 
FROM PESSOA_X_PESSOA_ENDERECO pxpe
where
 PXPE.id_pessoa =p.ID_PESSOA 
);

------------- FULL OUTER JOIN -------------
SELECT p.id_pessoa, P.NOME, E.id_endereco, E.LOGRADOURO
FROM PESSOA P
full OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (P.ID_PESSOA = PXPE.ID_PESSOA)
full OUTER JOIN ENDERECO_PESSOA e ON (E.ID_ENDERECO= PXPE.ID_ENDERECO);